// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package assets

import "fyne.io/fyne/v2"

var ResourceSwapPng = &fyne.StaticResource{
	StaticName: "swap.svg",
	StaticContent: []byte(
		"<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n<svg\n   width=\"24\"\n   height=\"24\"\n   viewBox=\"0 0 24 24\"\n   version=\"1.1\"\n   id=\"svg136\"\n   sodipodi:docname=\"swap.svg\"\n   inkscape:version=\"1.2.1 (9c6d41e, 2022-07-14)\"\n   xmlns:inkscape=\"http://www.inkscape.org/namespaces/inkscape\"\n   xmlns:sodipodi=\"http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd\"\n   xmlns=\"http://www.w3.org/2000/svg\"\n   xmlns:svg=\"http://www.w3.org/2000/svg\">\n  <defs\n     id=\"defs140\" />\n  <sodipodi:namedview\n     id=\"namedview138\"\n     borderopacity=\"0.25\"\n     inkscape:showpageshadow=\"2\"\n     inkscape:pageopacity=\"0.0\"\n     inkscape:pagecheckerboard=\"0\"\n     showgrid=\"false\"\n     inkscape:zoom=\"9.1482106\"\n     inkscape:cx=\"11.805587\"\n     inkscape:cy=\"12.13352\"\n     inkscape:window-width=\"1309\"\n     inkscape:window-height=\"456\"\n     inkscape:window-x=\"0\"\n     inkscape:window-y=\"38\"\n     inkscape:window-maximized=\"0\"\n     inkscape:current-layer=\"svg136\" />\n  <path\n     d=\"M0 0h24v24H0z\"\n     fill=\"none\"\n     id=\"path132\" />\n  <g\n     id=\"g441\"\n     transform=\"translate(0,0.327504)\">\n    <path\n       d=\"M 18.63,4.6 C 16.78,2.99 14.38,2 11.73,2 7.0799998,2 3.1499999,5.03 1.7699999,9.22 L 4.1299998,10 c 1.05,-3.19 4.0500001,-5.5 7.6000002,-5.5 1.95,0 3.73,0.72 5.12,1.88 L 13.23,10 h 9 V 1 Z\"\n       id=\"path134\" />\n    <path\n       d=\"m 5.3700003,18.744992 c 1.85,1.61 4.2500001,2.6 6.8999997,2.6 4.65,0 8.58,-3.03 9.96,-7.22 l -2.36,-0.78 c -1.05,3.19 -4.05,5.5 -7.6,5.5 -1.95,0 -3.7299996,-0.72 -5.1199996,-1.88 l 3.6199996,-3.62 h -9 v 9 z\"\n       id=\"path134-7\" />\n  </g>\n</svg>\n"),
}
